- name: Update package list
  apt:
    update_cache: yes

- name: Download MinIO binary
  get_url:
    url: https://dl.min.io/server/minio/release/linux-amd64/minio
    dest: /usr/local/bin/minio
    mode: '0755'

- name: Create MinIO system user
  user:
    name: minio-user
    system: yes
    shell: /sbin/nologin

- name: Create MinIO data directory
  file:
    path: /data
    state: directory
    owner: minio-user
    group: minio-user


- name: Copy MinIO systemd unit file
  copy:
    src: minio.service  
    dest: /etc/systemd/system/minio.service
    owner: root
    group: root
    mode: '0644'
  notify:
    - Reload systemd
  tags:
    - systemd_file

